### ISSUE TITLE
Pip install failing on MacOSX

### ISSUE THREAD

**Issue by brahmbhattspandan** [numenta/nupic#2357]
Installing NUPIC using PIP does not seem to work on MacOSX.
Using the command $pip install nupic gives an error as follow,

![screen shot 2015-07-28 at 5 45 09 pm](https://cloud.githubusercontent.com/assets/11262471/8944760/70bb3c76-3550-11e5-9767-44d44c9e424d.png)

Also the docker build is not working, but there is already an open issue for that.

**Comment by rhyolight** [comment]
Yes, I think this is a temporary problem happening because of pipeline issues. Please standby and I'll lte you know when you can retry.

**Comment by brahmbhattspandan** [comment]
Sure. Thanks.

**Comment by rhyolight** [comment]
@brahmbhattspandan In the meantime, you can compile from source? https://github.com/numenta/nupic/wiki/Running-NuPIC-on-OS-X

**Comment by rhyolight** [comment]
Depends on #2349.

**Comment by rhyolight** [comment]
Oh yeah you can try the Docker installation now, it should be working.

**Comment by brahmbhattspandan** [comment]
Its OS X Yosemite v 10.10.4

**Comment by brahmbhattspandan** [comment]
@rhyolight  Docker is working perfectly.

**Comment by tomoprime** [comment]
I also tried installing with pip on Yosemite with no success. I get no matching bindings errors nupic.bindings==0.1.0

I even went as far as:
Toms-MacBook-Pro:~ Tom$ brew install automake libtool cmake
Warning: automake-1.15 already installed
Warning: libtool-2.4.6 already installed
Warning: cmake-3.3.0 already installed
Toms-MacBook-Pro:~ Tom$ sudo easy_install pip
Password:
Searching for pip
Reading https://pypi.python.org/simple/pip/
Best match: pip 7.1.0
Downloading https://pypi.python.org/packages/source/p/pip/pip-7.1.0.tar.gz#md5=d935ee9146074b1d3f26c5f0acfd120e
Processing pip-7.1.0.tar.gz
Writing /tmp/easy_install-mHpHDt/pip-7.1.0/setup.cfg
Running pip-7.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-mHpHDt/pip-7.1.0/egg-dist-tmp-twO0Wj
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'
Adding pip 7.1.0 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
Toms-MacBook-Pro:~ Tom$ pip install nupic
/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already satisfied (use --upgrade to upgrade): nupic in /Library/Python/2.7/site-packages/nupic-0.2.7.dev0-py2.7.egg
Collecting asteval==0.9.1 (from nupic)
/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading asteval-0.9.1.tar.gz
Collecting coverage==3.7.1 (from nupic)
  Downloading coverage-3.7.1.tar.gz (284kB)
    100% |████████████████████████████████| 286kB 838kB/s 
Collecting mock==1.0.1 (from nupic)
  Downloading mock-1.0.1.tar.gz (818kB)
    100% |████████████████████████████████| 819kB 400kB/s 
Collecting ordereddict==1.1 (from nupic)
  Downloading ordereddict-1.1.tar.gz
Collecting pillow==2.3.0 (from nupic)
  Downloading Pillow-2.3.0.zip (2.4MB)
    100% |████████████████████████████████| 2.4MB 173kB/s 
Collecting psutil==1.0.1 (from nupic)
  Downloading psutil-1.0.1.tar.gz (156kB)
    100% |████████████████████████████████| 159kB 1.8MB/s 
Collecting pytest==2.4.2 (from nupic)
  Downloading pytest-2.4.2.tar.gz (553kB)
    100% |████████████████████████████████| 557kB 676kB/s 
Collecting pytest-cov==1.6 (from nupic)
  Downloading pytest-cov-1.6.tar.gz
Collecting pytest-xdist==1.8 (from nupic)
  Downloading pytest-xdist-1.8.zip
Collecting python-dateutil==2.1 (from nupic)
  Downloading python-dateutil-2.1.tar.gz (152kB)
    100% |████████████████████████████████| 155kB 1.5MB/s 
Collecting PyYAML==3.10 (from nupic)
  Downloading PyYAML-3.10.tar.gz (241kB)
    100% |████████████████████████████████| 241kB 1.0MB/s 
Collecting unittest2==0.5.1 (from nupic)
  Downloading unittest2-0.5.1.tar.gz (62kB)
    100% |████████████████████████████████| 65kB 2.6MB/s 
Collecting validictory==0.9.1 (from nupic)
  Downloading validictory-0.9.1.tar.gz
Collecting PyMySQL==0.6.2 (from nupic)
  Downloading PyMySQL-0.6.2-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 65kB 2.6MB/s 
Collecting DBUtils==1.1 (from nupic)
  Downloading DBUtils-1.1.tar.gz (109kB)
    100% |████████████████████████████████| 110kB 1.9MB/s 
Collecting pyproj==1.9.3 (from nupic)
  Downloading pyproj-1.9.3.tar.gz (2.7MB)
    100% |████████████████████████████████| 2.7MB 158kB/s 
Collecting prettytable==0.7.2 (from nupic)
  Downloading prettytable-0.7.2.tar.bz2
Collecting nupic.bindings==0.1.0 (from nupic)
  Could not find a version that satisfies the requirement nupic.bindings==0.1.0 (from nupic) (from versions: )
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external nupic.bindings to allow).
No matching distribution found for nupic.bindings==0.1.0 (from nupic)

**Comment by tomoprime** [comment]
Note I patched my SSL issue but I still get "No matching distribution found for nupic.bindings==0.1.0"

Toms-MacBook-Pro:~ Tom$ pip install nupic --upgrade --allow-external nupic.bindings
Requirement already up-to-date: nupic in /Library/Python/2.7/site-packages/nupic-0.2.7.dev0-py2.7.egg
Collecting asteval==0.9.1 (from nupic)
  Using cached asteval-0.9.1.tar.gz
Collecting coverage==3.7.1 (from nupic)
  Using cached coverage-3.7.1.tar.gz
Collecting mock==1.0.1 (from nupic)
  Using cached mock-1.0.1.tar.gz
Collecting ordereddict==1.1 (from nupic)
  Using cached ordereddict-1.1.tar.gz
Collecting pillow==2.3.0 (from nupic)
  Using cached Pillow-2.3.0.zip
Collecting psutil==1.0.1 (from nupic)
  Using cached psutil-1.0.1.tar.gz
Collecting pytest==2.4.2 (from nupic)
  Using cached pytest-2.4.2.tar.gz
Collecting pytest-cov==1.6 (from nupic)
  Using cached pytest-cov-1.6.tar.gz
Collecting pytest-xdist==1.8 (from nupic)
  Using cached pytest-xdist-1.8.zip
Collecting python-dateutil==2.1 (from nupic)
  Using cached python-dateutil-2.1.tar.gz
Collecting PyYAML==3.10 (from nupic)
  Using cached PyYAML-3.10.tar.gz
Collecting unittest2==0.5.1 (from nupic)
  Using cached unittest2-0.5.1.tar.gz
Collecting validictory==0.9.1 (from nupic)
  Using cached validictory-0.9.1.tar.gz
Collecting PyMySQL==0.6.2 (from nupic)
  Using cached PyMySQL-0.6.2-py2.py3-none-any.whl
Collecting DBUtils==1.1 (from nupic)
  Using cached DBUtils-1.1.tar.gz
Collecting pyproj==1.9.3 (from nupic)
  Using cached pyproj-1.9.3.tar.gz
Collecting prettytable==0.7.2 (from nupic)
  Using cached prettytable-0.7.2.tar.bz2
Collecting nupic.bindings==0.1.0 (from nupic)
  Could not find a version that satisfies the requirement nupic.bindings==0.1.0 (from nupic) (from versions: )
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external nupic.bindings to allow).
No matching distribution found for nupic.bindings==0.1.0 (from nupic)

**Comment by rhyolight** [comment]
Let's see what happens when https://github.com/numenta/nupic/pull/2435 runs...

**Comment by rhyolight** [comment]
@brahmbhattspandan @tomoprime This problem is not going to clear up until we have a NuPIC 0.2.7 release.

**Comment by wuxianliang** [comment]
"no match nupic.bindings == 0.10" does not appear when I upgrade to 0.2.7. But it appears when I upgrade to 0.2.8.
```shell
pip install nupic --upgrade
``
Could not find a version that satisfies the requirement nupic.bindings==0.1.0 (from nupic) (from versions: )
No matching distribution found for nupic.bindings==0.1.0 (from nupic)

**Comment by rhyolight** [comment]
I am aware of this problem and @akhilaananthram and I are working on it today. Thank you for the report.

**Comment by rhyolight** [comment]
@brahmbhattspandan @wuxianliang @tomoprime Yesterday we released [NuPIC 0.3.0](https://github.com/numenta/nupic/releases/tag/0.3.0), which hopefully fixed these installation problems. Please try the following for a binary installation on OS X:

    pip install nupic

And this for Linux:

    pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.1.5-cp27-none-linux_x86_64.whl
    pip install nupic
